apiVersion: v1
kind: Namespace
metadata:
  name: my-go-app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
  namespace: my-go-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
      - name: my-go-app
        image: caleybaek/toy-project-go
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-go-app
  labels:
    app: my-go-app
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-go-app
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 25
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-app
  namespace: my-go-app-namespace
spec:
  selector:
    app: my-go-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer

